# Autogenerated by devscripts/update-version.py

__version__ = '2025.07.15.100734'

RELEASE_GIT_HEAD = 'fd4290a5148136953e113b0ef9b3050adcc4089f'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'sugergirl520/yt-dlp'

ORIGIN = 'sugergirl520/yt-dlp'

_pkg_version = '2025.07.15.100734'
