# Autogenerated by devscripts/update-version.py

__version__ = '2025.07.25.074352'

RELEASE_GIT_HEAD = '596fa7c14a319f743f97734d67a73e489334ba46'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'sugergirl520/yt-dlp'

ORIGIN = 'sugergirl520/yt-dlp'

_pkg_version = '2025.07.25.074352'
