# Autogenerated by devscripts/update-version.py

__version__ = '2025.12.14.060155'

RELEASE_GIT_HEAD = 'd3ccced6b0067c12eee26f133c591194b7806253'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'sugergirl520/yt-dlp'

ORIGIN = 'sugergirl520/yt-dlp'

_pkg_version = '2025.12.14.060155'
